# docker-compose file
# for compose v2
# set your ip address in {YOUR_LOCAL_IP}
# docker-compose -f ./docker-compose.yml up -d

version: "2"

networks:
  app-tier:
    driver: bridge


services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    networks:
      - app-tier
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MAX_SESSION_TIMEOUT=100000
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    networks:
      - app-tier
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.10.0.199:9092 # {YOUR_LOCAL_IP}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=10.10.0.199:2181 # {YOUR_LOCAL_IP}
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=10.10.0.199:2181 # {YOUR_LOCAL_IP}
      - KAFKA_ADVERTISED_HOST_NAME=10.10.0.199 # {YOUR_LOCAL_IP}
      - JMX_PORT=9093
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000
    depends_on:
      - zookeeper
  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:stable
    networks:
      - app-tier
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Supplication.home=/kafkamanager
    environment:
      - ZK_HOSTS=10.10.0.199:2181 # {YOUR_LOCAL_IP}
      - APPLICATION_SECRET=letmein
    ports:
      - "9000:9000"
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - app-tier
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: datagenbase
      MYSQL_USER: juser
      MYSQL_PASSWORD: jpassword

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
      - app-tier
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql:
    driver: local
